<a href="https://colab.research.google.com/github/leonamcassemir0/iris-flower-classifier/blob/main/c%C3%B3digo_fluente_iris.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Instalando o Scikit-learn e plotando o gráfico

In [1]:
from sklearn import datasets
iris = datasets.load_iris()

# type(iris)
# print(iris.data)
# iris.feature_names
# list(iris.target_names)

"""
print(iris.target)
print(type(iris.data))
print(type(iris.target))
print(iris.data.shape)
print(iris.target.shape)
"""

X = iris.data
Y = iris.target

# Instalando o Pandas

In [2]:
import numpy as np
import pandas as pd

df_iris = pd.DataFrame(np.column_stack((iris.data, iris.target)), columns = iris.feature_names + ['target'])
# df_iris.describe()
df_iris

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     target  
0       0.0  
1       0.0  
2       0.0  
3       0.0  
4       0.0  
..      ...  
145     2.0  
146     2.0  
147     2.0  
148     2.0  
149     2.0  

[150 rows x 5 columns]

# Usando pandas na prática

In [3]:
import pandas as pd
import numpy as np

data = np.array(['a', 'b', 'c', 'd'])
s1 = pd.Series(data)
# s1

data2 = np.array(['e', 'F', 'g', 'h'])
s2 = pd.Series(data2, index=(70, 71, 72, 73))
#s2

data3 = {'a': 0., 'b': 1., 'c': 2.}
s3 = pd.Series(data3)
s3

a    0.0
b    1.0
c    2.0
dtype: float64

## DataFrame

DataFrame é uma estrutura de dados bidimensional, ou seja, os dados são alinhados de maneira tabular em linhas e colunas.

***pandas.DataFrame( data, index, columns, dtype, copy)***
1.   ***data:*** Dados assumem várias formas como ndarray, series, maps, lists, dict, constants e também outros DataFrames.
2.   ***index:*** Para rotular linhas, o índice a ser usado para o DataFrame resultante é opcional. Default np.arrange(n) se nenhum índice for passado.
3. ***columns:*** Para rotular colunas, a sintaxe padrão opcional é: np.arrange (n). Isso só é verdade se nenhum índice for passado.
4. ***dtype:*** Tipo de dados de cada coluna.
5. ***copy:*** Este comando (ou seja o que for) é usado para copiar dados, se o padrão for Falso.





In [4]:
# Data Frame vazio
df = pd.DataFrame()
#df

# Data Frame de lista
data = [1, 2, 3, 4, 5]
df1 = pd.DataFrame(data)
#df1

# Data Frame de lista de listas
data1 = [['Maria', 10], ['João', 12], ['Pedro', 15]]
df2 = pd.DataFrame(data1, columns = ['Nome', 'Idade'])
#df2

# Data Frame  de dicionários
data2 = {'Nome': ['Marcos', 'Paulo', 'Matheus', 'Pedro'], 'Pontuação': [10.0, 18.5, 45.75, 8.65]}
df3 = pd.DataFrame(data2, index=['rank1', 'rank2', 'rank3', 'rank4'])
# df3

# Data Frame de lista de dicionários
data3 = [{'a': 4.3, 'b': 10}, {'a': 3, 'b': 6.7, 'c': 1}]
df4 = pd.DataFrame(data3, index=['Primeiro', 'Segundo'], columns=['a', 'b'])
# df4

# Data Frame de dicionários de Series
dic = {'um' : pd.Series([1, 2, 3], index = ['a', 'b', 'c']),
   'dois' : pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])}
df5 = pd.DataFrame(dic)
#df5

## Selecionando coluna
# df5['um']

## Adicionando coluna
# df5['tres'] = df5['um'] + df5['dois']

## Excluindo coluna
"""
d = {'um' : pd.Series([1, 2, 3], index = ['a', 'b', 'c']),
   'dois' : pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd']),
   'três' : pd.Series([10, 20, 30], index = ['a','b','c'])}
df6 = pd.DataFrame(d)
df6
del df6['um']
df6
df6.pop('dois')
df6
"""

## Seleção, exclusão e adição de linha
r = {'um' : pd.Series([1, 2, 3], index = ['a', 'b', 'c']),
   'dois' : pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd']),
   'três' : pd.Series([10, 20, 30], index = ['a','b','c'])}
df7 = pd.DataFrame(r)
# df7.loc['b']
# df7.iloc[2:4]

## Adição de linhas
df = pd.DataFrame([[1, 2], [3, 4]], columns = ['a','b'])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns = ['a','b'])
df = df.append(df2)
df

AttributeError: 'DataFrame' object has no attribute 'append'

# K-nearest Neighbours

É um algoritmo simples e poderoso de aprendizado supervisionado usado para classificação e regressão. Ele funciona encontrando os k vizinhos mais próximos de um ponto novo (baseado em uma métrica de distância, como a euclidiana) e determinando sua categoria ou valor com base nesses vizinhos.

***Exemplo prático:*** Imagine que você quer classificar uma fruta como maçã ou laranja. Você tem um gráfico onde cada ponto representa frutas conhecidas, com características como peso e cor. Se você inserir uma nova fruta, o KNN vai olhar para as frutas mais próximas no gráfico (os vizinhos) e decidir com base na maioria. Se 3 dos 5 vizinhos forem maçãs, a nova fruta será classificada como maçã.

In [12]:
from sklearn import datasets
import pandas as pd

iris = datasets.load_iris()
irs = pd.DataFrame(iris.data, columns=iris.feature_names)
irs['class'] = iris.target
irs.head()

x = irs.iloc[:, :-1].values
y = irs.iloc[:, 4].values

## Divisão em conjunto de teste e de treino

In [17]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.20)

### Normalização

In [18]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

## Treinamentos e previsões

In [24]:
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(x_train, y_train)

y_pred = classifier.predict(x_test)

### Avaliando o algoritmo

In [26]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 8  0  0]
 [ 0 10  0]
 [ 0  0 12]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        12

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

